// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/8/2024, 23:06:14
const configMerger = require("C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/plugins/**/*.{js,ts,mjs}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/composables/**/*.{js,ts,mjs}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/utils/**/*.{js,ts,mjs}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/desarrolloWeb/proyectos/alexis/alexis-web-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
